project:
  type: website
  output-dir: _site

website:
  title: "Your Name - Product Builder Portfolio"
  navbar:
    background: primary
    left:
      - icon: linkedin
        href: https://linkedin.com/in/your-profile
      - icon: github
        href: https://github.com/your-username
      - icon: envelope
        href: mailto:your.email@example.com
    center:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Projects
        menu:
          - href: projects/project-1.qmd
            text: Portfolio Development
          - href: projects/project-2.qmd
            text: Business Case Presentation
          - href: projects/project-3.qmd
            text: Project 3
          - href: projects/project-4.qmd
            text: Project 4
          - href: projects/project-5.qmd
            text: Project 5
          - href: projects/project-6.qmd
            text: Project 6

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
